### ISSUE TITLE
Is this still working

### ISSUE THREAD

**Issue by adrish96** [ammgws/hangouts_client#3]
I read that google has stopped supporting XMPP for hangouts, so it this code still working?

**Comment by ammgws** [comment]
It's still working.

**Comment by adrish96** [comment]
I tried cloning the code and running it.
To run the code I used the snippet in the readme file, 
``if __name__=='__main__':
    config_file = 'config.ini'
    hangouts=HangoutsClient(config_file)
    if hangouts.connect():
        hangouts.process(block=False)
    else:
        print('Failed to connect to Hangouts!')``
I get the following error on trying to run it:
``Traceback (most recent call last):
  File "hangoutsclient.py", line 169, in <module>
    hangouts=HangoutsClient(config_file)
TypeError: __init__() missing 1 required positional argument: 'client_secret'
``
Whereas in the config file I have inserted the 'client_secret' (I've checked this)
How do I solve this?

**Comment by ammgws** [comment]
Sorry about that, the snippet is old. Try the below:

```python
from configparser import ConfigParser
import os.path
from pathlib import Path
from time import sleep

from hangoutsclient import HangoutsClient

if __name__=='__main__':
    config_file = 'config.ini'
    config = ConfigParser()
    config.read(config_file)
    client_id = config.get('Hangouts', 'client_id')
    client_secret = config.get('Hangouts', 'client_secret')
    token_file = os.path.join('hangouts_cached_token')
    if not os.path.isfile(token_file):
        Path(token_file).touch()

    hangouts = HangoutsClient(client_id, client_secret, token_file)
    if hangouts.connect():
        hangouts.process(block=False)
        sleep(5)  # need time for Hangouts roster to update
        hangouts.send_to_all("test123")
        hangouts.disconnect(wait=True)
    else:
        print('Failed to connect to Hangouts!')
```

**Comment by adrish96** [comment]
So now I'm getting this message:
``
https://accounts.google.com/o/oauth2/v2/auth?client_id=%27410256760339422-3rfhgjjkgufnpvmr38nf6afi98hgmibu0oivn34.apps.googleusercontent.com%27&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgoogletalk+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&access_type=offline``
``Enter auth code from the above link:``
and the corresponding webpage shows this error:
``
401. That’s an error.
Error: invalid_client
The OAuth client was not found.
``

**Comment by ammgws** [comment]
Hmm, looks like an issue with the config. Is there a stray apostrophe ( ' ) in front of your client ID in the config file?

**Comment by adrish96** [comment]
No, I'm pretty sure thats not the case. I've rechecked this multiple times.

**Comment by ammgws** [comment]
Then the only thing I can think of is that there is perhaps something is wrong with the OAuth credentials you created, since the URL that is printed in the terminal is dependent only on the client ID specified in the config.

When I get home later tonight I'll try with a new account in case something changed.

**Comment by adrish96** [comment]
Okay man, thanks for the help.
In the meanwhile I'll try creating new credentials and try again. This seems to be the only bottleneck in the program flow.

**Comment by ammgws** [comment]
Just tried it with a fresh account (G-Suite account but it should be the same for a standard Google account) and it worked fine.

This is how I created the OAuth credentials:
1) Create a project then go to the Credentials page and select 'OAuth client ID' from the dropdown
![image](https://user-images.githubusercontent.com/20397027/54929198-88a8f000-4f58-11e9-9a2b-d6663339d612.png)
 If it says you need to first create a consent screen then set the application type to "Internal", enter something for the application name then scroll to the bottom and click Save. (no need to bother with the Scopes section on this page)
![image](https://user-images.githubusercontent.com/20397027/54929991-d114dd80-4f59-11e9-9b96-1b23ed009070.png)

2) Choose 'Other'
![image](https://user-images.githubusercontent.com/20397027/54929412-d7568a00-4f58-11e9-83fc-de5fb1469da9.png)

3) Success screen
![image](https://user-images.githubusercontent.com/20397027/54929430-e2a9b580-4f58-11e9-8983-35d81b1a446e.png)

4) Copy paste the client ID and secret into the config file and this is what the URL should take you to:
![image](https://user-images.githubusercontent.com/20397027/54929512-05d46500-4f59-11e9-86c2-51f957995ab9.png)

**Comment by adrish96** [comment]
I followed the exact same steps, just doesn't work in my case. Always end up on the error 401 page on clicking the link! 
I'm at a loss here :(
This is the page I end up on:
![Screenshot from 2019-03-25 21-42-45](https://user-images.githubusercontent.com/10412280/54936047-9e61e980-4f47-11e9-9b6d-9866b9c58d09.png)

**Comment by ammgws** [comment]
Hmm I'm not sure what else we can try... perhaps creating a new project in the API console?

Also, I know you said you checked many times but are there really no quote marks in your config.ini? The URL that's showing up in your terminal has apostrophes in it (percent encoded as `%27`), and as far as I know the only place it could possibly come from is the client Id section from the config:
![image](https://user-images.githubusercontent.com/20397027/54938995-d2023b00-4f6a-11e9-848d-fb3333f38327.png)

**Comment by adrish96** [comment]
Hey, I was actually using apostrophes in the config file, removed them. 
A strange error is coming up now:
``ERROR:sleekxmpp.xmlstream.xmlstream:Connection error.``
``ERROR:sleekxmpp.basexmpp:<TagSet object at 0x7f8a82a6b9b0 tags 0:32:16> not in asn1Spec: <OctetString schema object at 0x7f8a82a8a8d0 tagSet <TagSet object at 0x7f8a835d1550 tags 0:0:4> encoding iso-8859-1>
Traceback (most recent call last):
  File "/home/adrish/Documents/python codes/hangouts_client/venv/lib/python3.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1492, in _process
    if not self.__read_xml():
  File "/home/adrish/Documents/python codes/hangouts_client/venv/lib/python3.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1564, in __read_xml
    self.__spawn_event(xml)
  File "/home/adrish/Documents/python codes/hangouts_client/venv/lib/python3.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1632, in __spawn_event
    handler.prerun(stanza_copy)
  File "/home/adrish/Documents/python codes/hangouts_client/venv/lib/python3.6/site-packages/sleekxmpp/xmlstream/handler/callback.py", line 64, in prerun
    self.run(payload, True)
  File "/home/adrish/Documents/python codes/hangouts_client/venv/lib/python3.6/site-packages/sleekxmpp/xmlstream/handler/callback.py", line 76, in run
    self._pointer(payload)
  File "/home/adrish/Documents/python codes/hangouts_client/venv/lib/python3.6/site-packages/sleekxmpp/features/feature_starttls/starttls.py", line 64, in _handle_starttls_proceed
    if self.xmpp.start_tls():
  File "/home/adrish/Documents/python codes/hangouts_client/venv/lib/python3.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 889, in start_tls
    cert.verify(self._expected_server_name, self._der_cert)
  File "/home/adrish/Documents/python codes/hangouts_client/venv/lib/python3.6/site-packages/sleekxmpp/xmlstream/cert.py", line 134, in verify
    cert_names = extract_names(raw_cert)
  File "/home/adrish/Documents/python codes/hangouts_client/venv/lib/python3.6/site-packages/sleekxmpp/xmlstream/cert.py", line 73, in extract_names
    asn1Spec=OctetString())[0]
  File "/home/adrish/Documents/python codes/hangouts_client/venv/lib/python3.6/site-packages/pyasn1/codec/ber/decoder.py", line 1530, in __call__
    '%s not in asn1Spec: %r' % (tagSet, asn1Spec)
pyasn1.error.PyAsn1Error: <TagSet object at 0x7f8a82a6b9b0 tags 0:32:16> not in asn1Spec: <OctetString schema object at 0x7f8a82a8a8d0 tagSet <TagSet object at 0x7f8a835d1550 tags 0:0:4> encoding iso-8859-1>
``

UPDATE: changed versions of modules to ``sleekxmpp==1.3.2``, ``pyasn1==0.3.7`` and ``pyasn1-modules==0.1.5`` and the error was resolved 
Now I'm getting ``ERROR:sleekxmpp.xmlstream.xmlstream:Error reading from XML stream.`` though. Have you any idea about this?

**Comment by ammgws** [comment]
Can you show me the output of `pip list`?

**Comment by adrish96** [comment]
This is the output of ``pip list`` :
``Package        Version ``
``-------------- --------``
``certifi        2019.3.9``
``chardet        3.0.4   ``
``configparser   3.7.4   ``
``google-auth    0.1.5   ``
``idna           2.8     ``
``pathlib        1.0.1   ``
``pip            19.0.3  ``
``pyasn1         0.3.7   ``
``pyasn1-modules 0.1.5  `` 
``requests       2.21.0  ``
``setuptools     40.8.0  ``
``sleekxmpp      1.3.2   ``
``urllib3        1.24.1  ``
``wheel          0.33.1  ``

**Comment by adrish96** [comment]
Hi, apparently the test message was delivered  yesterday, the ``ERROR:sleekxmpp.xmlstream.xmlstream:Error reading from XML stream.`` error is not coming anymore, this is strange!
The ``send_to()`` an ``send_to_all()`` funcs work fine, the ``contact_list()`` func is returning an error 
``Traceback (most recent call last):``
 `` File "hangoutsclient.py", line 185, in <module>``
``   print(hangouts.contacts_list())``
``TypeError: 'RosterNode' object is not callable``

This is fine though, I needed the ``send_to()`` functionality only. 
Also, can this code be extended to receive messages too?

**Comment by ammgws** [comment]
It's a property so it should be `print(hangouts.contacts_list)`. 
e.g. Print all the contacts:
```python
contacts = hangouts.contacts_list
    for contact in contacts:
    print(contact)
```

If you set `send_only` to false and override the `message` function then you can receive and reply to messages too. Should be something like the below:
```python
def custom_msg_handler(self, sender, text):
    #write your function here
    print(f"{sender} sent me this message: {text}")

hangouts = HangoutsClient(client_id, client_secret, token_file, send_only=False)
hangouts.message = custom_msg_handler
```

**Comment by adrish96** [comment]
I tried this, is'nt working:
```
def recv_message(self, msg):
    if msg['type'] in ('chat', 'normal'):
        print("{} says: {}", format(msg['from'], msg['body']))

self.add_event_handler('message', self.recv_message)
hangouts = HangoutsClient(client_id, client_secret, token_file, send_only=False)
hangouts.message = hangouts.recv_message
```
Can you help me with this?

**Comment by ammgws** [comment]
The function doesn't look right, iirc the msg object isn't passed on to the message function. Try changing it to the one I posted above. Also I'm not sure why there's a "self" in there. Are you modifying the Hangouts client code instead of just overriding the function?

Might be easier if you can show me the whole code in a gist or something.

**Comment by adrish96** [comment]
[here](https://gist.github.com/adrish96/02f20894a9c3521ebb7a0403a7a98a5b) is my code in a gist.
I did try the code with exactly what you posted above, it didn't work, didn't return any error either, I checked the log file 
```
Traceback (most recent call last):
  File "/home/adrish/Documents/python codes/hangouts_client/venv/lib/python3.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1708, in _event_runner
    func(*args)
TypeError: recv_message() missing 1 required positional argument: 'text'
2019-03-27 12:22:52,519 - Waiting for </stream:stream> from server
2019-03-27 12:22:52,659 - Error reading from XML stream.
```
I tried referring to [this](https://stackoverflow.com/a/13126830) StackOverflow answer.

**Comment by adrish96** [comment]
I had a conversation on sleek@conference.jabber.org, I was told that the receiving messages part is not working as Hangouts doesn't support XMPP protocol anymore.
I was pointed to [this](https://support.google.com/a/answer/4564211?hl=en), check the "Supports SIP/ XMPP federation" in the table

**Comment by ammgws** [comment]
As far as I know federation just means being able to communicate with non-Google XMPP services. If you're using it between Hangouts users then it should work. Let me try later tonight or this week.

**Comment by adrish96** [comment]
Okay, do update this thread. I'm stuck with my project, I'd love it if you try it out tonight :-)

**Comment by ammgws** [comment]
No issues with receiving messages: ![image](https://user-images.githubusercontent.com/20397027/55077774-edd91e80-50db-11e9-95f0-f5c6e0da24d2.png)

Check the test code [here](https://gist.github.com/ammgws/7d3ac157ff5af85a38469369777f2587#file-hangouts_test-py). 

You might need to install the below if not already:
```
pip install git+git://github.com/ammgws/hangouts_client.git
pip install git+git://github.com/ammgws/google_auth.git
```

**Comment by adrish96** [comment]
Thanks a lot for the help man! Appreciate it :smile: 
I plan to integrate the sending and receiving in the same program. Once done, do you want me to create a PR?

**Comment by ammgws** [comment]
Sure, no harm in that.

By the way, the reason I made it that you have to subclass HangoutsClient and override the message function is because everyone will have a different use case for how they will deal with messages. I can add the ability to reply to messages to the class if you need that. What were you thinking of?

**Comment by ammgws** [comment]
I just pushed an [update](https://github.com/ammgws/hangouts_client/commit/5f6b985536c7e6477380fee152950bec44992d6e) that lets you access the message stanza object so you can reply to messages.

Test code [here](https://gist.github.com/ammgws/7d3ac157ff5af85a38469369777f2587). Works well for me.

**Comment by adrish96** [comment]
Yeah, this works well for me too.

**Comment by adrish96** [comment]
Am I doing this the right way?
```
    def _message(self, msg):
        """Process incoming message stanzas.

        Args:
            msg -- The received message stanza as SleekXMPP Message object.
        """
        if msg['type'] in ('chat', 'normal'):
            self.message(msg['from'].bare, msg['body'])


    def message(self, sender, text):
        """Override this method."""
        print(f"{sender} sent me this message: {text}")
        #pass
```

**Comment by ammgws** [comment]
Did you try the code [here](https://gist.github.com/ammgws/7d3ac157ff5af85a38469369777f2587)?

All you need to do is play with the message function that starts on line 15.

**Comment by adrish96** [comment]
Yeah, I did.
Thanks for the help. 
Just that I used the send_to() func to send the message.

**Comment by ammgws** [comment]
OK no worries.

**Comment by adrish96** [comment]
Whenever a new message comes in there is this message being logged,
```
Traceback (most recent call last):
  File "/home/c-adrish.ghosh/hangouts_api/venv/lib64/python3.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1708, in _event_runner
    func(*args)
  File "/home/c-adrish.ghosh/hangouts_api/hangoutsIntegrations.py", line 81, in _message
    self.message(msg['from'].bare, msg['body'])
  File "api.py", line 40, in message
    tokens[token]['message']=msg
KeyError: 'adrish.ghosh'
2019-05-01 14:15:08,526 - Error handling {jabber:client}message stanza
```
But in-spite of the error I'm able to get the message and do what I need to do.
